services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: arsnova3
  MYSQL_ROOT_PASSWORD: arsnova3_prototype
  WAR_FILE: target/scala-2.11/ARSnova-*.jar

stylecheck:
  tags:
    - sbt
  script:
    - sbt scalastyle
    - sbt test:scalastyle

test:
  tags:
    - sbt
  script:
    # Execute your project's tests
    - sbt clean test

package:
  stage: build
  tags:
    - sbt
  artifacts:
    paths:
      - $WAR_FILE
  script:
    - sbt assembly
